### PR TITLE
Jison-based grammar

### PR DESCRIPTION
**Pull request by dirk**

### CODE REVIEW

**Comment by dirk** [comment]
@ryngonzalez: Ready for your review!

**Comment by dirk** [comment]
Actually nevermind, I'm not yet satisfied with how the parsers are stacking up performance-wise.

**Comment by dirk** [comment]
@ryngonzalez: Ready for review again.

**Comment by ryngonzalez** [comment]
Could you rebase this?

**Comment by ryngonzalez** [comment]
TLDR:

- Jison grammar definition is easier to read
- :+1: to the speed improvement

LGTM after rebase!

**Pull request merged**
