### PR TITLE
LLVM target compilation

### PR DESCRIPTION
**Pull request by dirk**
##### Required for first version of compiler
- [x] Garbage collector ([BDW](https://en.wikipedia.org/wiki/Boehm_garbage_collector)?)
- [x] Class structures (build `struct` with correct slots)
- [x] Class instance methods (`this` as first argument to method function)
- [x] Basic functions
- [x] Primitive operators (+,-,/, etc. on integers and strings)
- [x] Implement standard library (see #32)
- [x] "Headers" for and linking of the standard library during compilation
- [x] Basic modules support

##### Would be nice to have
- [ ] Multi functions (figure out if we're doing any form of RTTI or forcing it to be static for now)
- [x] Tooling to create static library (object file is good enough for now) of standard library

### CODE REVIEW

**Comment by dirk** [comment]
@ryngonzalez Could you give this a once-over? Would like to get this merged and open up fresh issues for distinct topics in our LLVM support (documentation, multiple dispatch, improvements to chain nodes, etc.).

**Comment by ryngonzalez** [comment]
Just gave this a once over, merge at will!

**Comment by dirk** [comment]
Merged!

Fun note: amazingly, the **only** conflicted file was `examples/simple.hb`. That was a bit surprising!

**Comment by ryngonzalez** [comment]
Wow, that's crazy!



— Ryan Gonzalez

**Pull request merged**
